version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages
      prefix: "[Dependabot] npm"
    labels:
      # Add these labels to the Generated PR
      - "npm"
      - "dependencies"
      - "update"
    ignore:
      # Ignore major updates for these dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "redux"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
      - dependency-name: "babel"
        update-types: ["version-update:semver-major"]